/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    NutAvatar: typeof import('@nutui/nutui')['Avatar']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCard: typeof import('@nutui/nutui')['Card']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
    UseFactoryModal: typeof import('./../src/components/Modal/src/hooks/useFactoryModal.tsx')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
