/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./src/components/basic/BaseHeader.vue')['default']
    DashboardLayout: typeof import('./src/layouts/DashboardLayout.vue')['default']
    DashboardSidebar: typeof import('./src/layouts/DashboardSidebar.vue')['default']
    Demo: typeof import('./src/views/demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Forbidden: typeof import('./src/views/common/Forbidden.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    Menubar: typeof import('./src/components/widgets/Menubar.vue')['default']
    NotFound: typeof import('./src/views/common/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/layouts/Sidebar.vue')['default']
    SvgIcon: typeof import('./src/components/widgets/SvgIcon.vue')['default']
  }
}
