/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Analysis: typeof import('./src/views/dashboard/Analysis.vue')['default']
    Config: typeof import('./src/views/system/Config.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Forbidden: typeof import('./src/views/common/Forbidden.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Index: typeof import('./src/views/Index.vue')['default']
    List: typeof import('./src/views/user/List.vue')['default']
    Log: typeof import('./src/views/system/Log.vue')['default']
    Menu: typeof import('./src/views/system/Menu.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    NotFound: typeof import('./src/views/common/NotFound.vue')['default']
    Overview: typeof import('./src/views/dashboard/Overview.vue')['default']
    Role: typeof import('./src/views/user/Role.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/widgets/SvgIcon.vue')['default']
  }
}

// For TSX support
declare global {
  const Analysis: typeof import('./src/views/dashboard/Analysis.vue')['default']
  const Config: typeof import('./src/views/system/Config.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElAvatar: typeof import('element-plus/es')['ElAvatar']
  const ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
  const ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElHeader: typeof import('element-plus/es')['ElHeader']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const Forbidden: typeof import('./src/views/common/Forbidden.vue')['default']
  const Home: typeof import('./src/views/Home.vue')['default']
  const Index: typeof import('./src/views/Index.vue')['default']
  const List: typeof import('./src/views/user/List.vue')['default']
  const Log: typeof import('./src/views/system/Log.vue')['default']
  const Menu: typeof import('./src/views/system/Menu.vue')['default']
  const MenuItem: typeof import('./src/components/MenuItem.vue')['default']
  const NotFound: typeof import('./src/views/common/NotFound.vue')['default']
  const Overview: typeof import('./src/views/dashboard/Overview.vue')['default']
  const Role: typeof import('./src/views/user/Role.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SvgIcon: typeof import('./src/components/widgets/SvgIcon.vue')['default']
}